### ISSUE TITLE
use multiple gpu

### ISSUE THREAD

**Issue by sorrowyn** [HCPLab-SYSU/HCP-MLR-PL#1]
Can't use multiple gpu to train 
`OMP_NUM_THREADS=8 MKL_NUM_THREADS=8 CUDA_VISIBLE_DEVICES=0,1 python SST.py \`

![图片](https://user-images.githubusercontent.com/19569162/150287017-f6208c46-8a7a-4cb9-8b6e-c7864c11383e.png)

**Comment by putao537** [comment]
> Can't use multiple gpu to train `OMP_NUM_THREADS=8 MKL_NUM_THREADS=8 CUDA_VISIBLE_DEVICES=0,1 python SST.py \`
> 
> ![图片](https://user-images.githubusercontent.com/19569162/150287017-f6208c46-8a7a-4cb9-8b6e-c7864c11383e.png)

Sorry, it does not support to use of multiple gpu.
