### ISSUE TITLE
Some questions about Comparison with SOTAs in your paper

### ISSUE THREAD

**Issue by STARK1234** [HCPLab-SYSU/HCP-MLR-PL#3]
Thanks for your great paper!

SSGRL and KGGR are also your previous works. I think KGGR is the journal version of SSGRL. They show different performances in Table 1 where KGGR is much  better than SSGRL. What is the difference between KGGR and SSGRL?

In Citation of https://github.com/HCPLab-SYSU/SSGRL, KGGR is also listed, but I do not find the code of KGGR. Could you please provide the reproducible code of KGGR?

**Comment by putao537** [comment]
> Thanks for your great paper!
> 
> SSGRL and KGGR are also your previous works. I think KGGR is the journal version of SSGRL. They show different performances in Table 1 where KGGR is much better than SSGRL. What is the difference between KGGR and SSGRL?
> 
> In Citation of https://github.com/HCPLab-SYSU/SSGRL, KGGR is also listed, but I do not find the code of KGGR. Could you please provide the reproducible code of KGGR?

Sorry, I didn't save the code files of the other comparison methods. Lucky, I find a previous code file that maybe can help you.

As you can find in the paper, the difference between KGGR and SSGRL is introducing classifier weight to guide the prototype representation propagation.  

Please feel free to reopen this issue if you still have any questions.

![image](https://user-images.githubusercontent.com/22413761/175511641-85dfefcb-69a8-4ed7-aaf6-0883267b19be.png)

**Comment by STARK1234** [comment]
Thanks very much, you have solved my doubts about KGGR very well.
