### ISSUE TITLE
SARB-journal bug

### ISSUE THREAD

**Issue by hugh920** [HCPLab-SYSU/HCP-MLR-PL#6]
Dear author, here I am again. I found many bugs when running the code of SARB-journal recently. Did you not run the code before uploading it? And, may I ask which is the more advanced version of SARB and SARB-Journal?

**Comment by putao537** [comment]
> Dear author, here I am again. I found many bugs when running the code of SARB-journal recently. Did you not run the code before uploading it? And, may I ask which is the more advanced version of SARB and SARB-Journal?

Sorry for the confusion. Before updating the code, we run the code but didn't find any bug.
We recently modify the journal version of SARB. After that, we will update the code.
